---
    # This file starts all the React applications with live-reload. Ports are incrementing (3001, 3002...)
    version: "3.7"
    services:
      react-bootstrap:
        build: "./react-bootstrap"
        ports:
          - 3001:3000
        volumes:
          - ./react-bootstrap:/app
          # Anonymous volume to prevent overwrite
          - /app/node_modules
        environment:
          CHOKIDAR_USEPOLLING: "true"
    
      ant-design:
        build: "./ant-design"
        ports:
          - 3002:3000
        volumes:
          - ./ant-design:/app
          # Anonymous volume to prevent overwrite
          - /app/node_modules
        environment:
          CHOKIDAR_USEPOLLING: "true"
    
      chakra-ui:
        build: "./chakra-ui"
        ports:
          - 3003:3000
        volumes:
          - ./chakra-ui:/app
          # Anonymous volume to prevent overwrite
          - /app/node_modules
        environment:
          CHOKIDAR_USEPOLLING: "true"
    
      grommet:
        build: "./grommet"
        ports:
          - 3004:3000
        volumes:
          - ./grommet:/app
          # Anonymous volume to prevent overwrite
          - /app/node_modules
        environment:
          CHOKIDAR_USEPOLLING: "true"
    
      prime-react:
        build: "./prime-react"
        ports:
          - 3005:3000
        volumes:
          - ./prime-react:/app
          # Anonymous volume to prevent overwrite
          - /app/node_modules
        environment:
          CHOKIDAR_USEPOLLING: "true"
    
      react-suite:
        build: "./react-suite"
        ports:
          - 3006:3000
        volumes:
          - ./react-suite:/app
          # Anonymous volume to prevent overwrite
          - /app/node_modules
        environment:
          CHOKIDAR_USEPOLLING: "true"
    